### ISSUE TITLE
Amazing mod! Found this bug after 3 repeated playthroughs.

### ISSUE THREAD

**Issue by AnEducatedGuess** [Manello/hla_mod_XenThug#1]
Hey! Love this mod, it is insanely fun and it uses the resources so creatively! It's given an extended life to an already great game, I thank you very much.

I found a bug! When it hits wave 16, a headcrab by the handcart carrying cement bags stays there, in idle animation, completely unresponsive and unkillable. I don't know if this is the headcrab you mention in the patch notes. 

Running on RX580 Ryzen 2700

**Comment by Manello** [comment]
Yup, that is a known Bug, and I've tried many things to fix it.
I am of course not 100% sure, but it seems like it is a problem with the Game/the Engine itself. 
It is always a headcrab dismounted from a zombie, and there is really no reason it should go immortal. 

It might be a timing problem, as the game tends to spawn enemies asynchronusly (and my script is modyfying it in another thread at the same time?) The Problem does not always appear on wave 16, only sometimes. (Never if you kill the last zombie of wave 15 with a grenade as it kills the crab as well)

**Comment by Manello** [comment]
Solved in Warehouse 1.3 / Mod 0.4+
