### ISSUE TITLE
Map Design Flaw

### ISSUE THREAD

**Issue by abbozkir** [Manello/hla_mod_XenThug#5]
First of all, thanks for the mod, it's so fun. There is a game ending design flaw, it's a trap-like space that if you go in, you can't climb back and you have to finish your session. I don't know if it's known already but I had to mention because I've lost my progress twice when I fall there.

The higher area that you can climb by some barrels and then a wooden plate (not SMG's location, opposite corner). There is a space between wooden crates that you fit, if you fall in there you can't climb back because it's too high, you can't also walk outside because you can't fit the openings, you just trapped there.

I also killed myself while opening the door towards me, I don't know what happened and I didn't try to reproduce the bug, just fyi

![check-out-this-half-life-alyx-horde-mode-mod_feature](https://user-images.githubusercontent.com/25688886/80099037-7b549f80-8576-11ea-92a1-834f67bddebc.jpg)
.

**Comment by Manello** [comment]
Solved in Warehouse 1.3
